"""
Rawbank Sentient Fraud Intelligence Platform - Rules Metadata & Catalog
Defines rules FR-01 through FR-20 and Counter-Evidence CE-01 through CE-05.
"""

RULES_CATALOG = {
    'FR-01': {
        'id': 'FR-01',
        'title': 'Amount >= 5x Customer Median',
        'category': 'Value Anomaly',
        'weight': 12,
        'severity': 'MEDIUM',
        'description': 'Transaction outbound value is at least 5 times the customer 90-day transaction median baseline.',
        'sop': 'Verify source of funds and customer spending pattern; check if prior declaration was made.',
    },
    'FR-02': {
        'id': 'FR-02',
        'title': 'Amount >= 10x Customer Median',
        'category': 'Extreme Value Anomaly',
        'weight': 20,
        'severity': 'HIGH',
        'description': 'Outbound amount exceeds 10 times the historical median transaction value.',
        'sop': 'Urgent outbound verification required. Place immediate supervisory hold if recipient is unverified.',
    },
    'FR-03': {
        'id': 'FR-03',
        'title': 'New Beneficiary',
        'category': 'Counterparty Risk',
        'weight': 12,
        'severity': 'MEDIUM',
        'description': 'Beneficiary was registered within 0-2 days or has zero prior completed transactions with this customer.',
        'sop': 'Check beneficiary verification status, relationship declaration, and counterparty banking rail.',
    },
    'FR-04': {
        'id': 'FR-04',
        'title': 'New / Untrusted Device',
        'category': 'Device Risk',
        'weight': 12,
        'severity': 'MEDIUM',
        'description': 'Transaction executed from a device first seen today or flagged as untrusted.',
        'sop': 'Examine device fingerprint, hardware OS, and customer registered device binding.',
    },
    'FR-05': {
        'id': 'FR-05',
        'title': '3+ Failed Logins in 30 Min',
        'category': 'Credential Attack',
        'weight': 14,
        'severity': 'HIGH',
        'description': 'Rapid repeated authentication failures preceding successful login within a 30-minute window.',
        'sop': 'Review authentication telemetry; check for automated brute-force or credential-stuffing patterns.',
    },
    'FR-06': {
        'id': 'FR-06',
        'title': 'Password Reset within 24h',
        'category': 'Account Takeover Risk',
        'weight': 10,
        'severity': 'MEDIUM',
        'description': 'Customer account underwent credential or PIN reset within the preceding 24 hours.',
        'sop': 'Confirm reset channel (Branch callback, OTP, or self-service) and verify phone number continuity.',
    },
    'FR-07': {
        'id': 'FR-07',
        'title': 'Recent SIM Swap <= 7 Days',
        'category': 'Identity Theft',
        'weight': 8,
        'severity': 'MEDIUM',
        'description': 'Telecom provider telemetry flags SIM card swap activity within the last 7 calendar days.',
        'sop': 'Trigger out-of-band biometric or in-branch verification before releasing held funds.',
    },
    'FR-08': {
        'id': 'FR-08',
        'title': '4+ Transactions in 10 Min',
        'category': 'Velocity Burst',
        'weight': 14,
        'severity': 'HIGH',
        'description': 'Velocity spike with 4 or more rapid debits executed within a 10-minute sliding window.',
        'sop': 'Automated velocity throttle applied. Investigate automated script or forced cash-out.',
    },
    'FR-09': {
        'id': 'FR-09',
        'title': 'Abnormal 1-Hour Outbound Value',
        'category': 'Cash-out Velocity',
        'weight': 12,
        'severity': 'HIGH',
        'description': 'Cumulative 1-hour outbound debits exceed 4x customer median or surpass $2,500 across rapid transfers.',
        'sop': 'Inspect potential account drainage; assess total cumulative outbound exposure.',
    },
    'FR-10': {
        'id': 'FR-10',
        'title': 'Impossible Travel',
        'category': 'Geolocation Anomaly',
        'weight': 20,
        'severity': 'CRITICAL',
        'is_hard_trigger': True,
        'description': 'Physical touchpoints or IP locations changed over >400 km in under 90 minutes (e.g., Kinshasa to Lubumbashi).',
        'sop': 'Hard trigger. Immediate device token revocation and card/channel freeze.',
    },
    'FR-11': {
        'id': 'FR-11',
        'title': 'Unusual Location / Country',
        'category': 'Geolocation Anomaly',
        'weight': 7,
        'severity': 'LOW',
        'description': 'Transaction initiated from a foreign country or remote province inconsistent with customer home residence.',
        'sop': 'Check customer travel notice, diaspora profile, or roaming telemetry.',
    },
    'FR-12': {
        'id': 'FR-12',
        'title': 'VPN / Proxy Signal',
        'category': 'Network Anonymity',
        'weight': 5,
        'severity': 'LOW',
        'description': 'Client IP address matches known commercial VPN, data center proxy, or TOR exit node list.',
        'sop': 'Inspect ASN, ISP type, and proxy risk score. Combine with device fingerprint trust.',
    },
    'FR-13': {
        'id': 'FR-13',
        'title': 'Shared Device Across 3+ Accounts',
        'category': 'Multi-Accounting Syndicate',
        'weight': 13,
        'severity': 'HIGH',
        'description': 'The consumer digital device has accessed 3 or more unrelated customer accounts in 30 days.',
        'sop': 'Syndicate investigation. Cross-reference all linked accounts for coordinated fraud ring.',
    },
    'FR-14': {
        'id': 'FR-14',
        'title': 'Mule Beneficiary (5+ Senders)',
        'category': 'Mule Network',
        'weight': 15,
        'severity': 'CRITICAL',
        'description': 'Beneficiary received inbound payments from 5 or more distinct unrelated customers within 30 days.',
        'sop': 'Money mule alert. Block counterparty beneficiary across all channels and file STR.',
    },
    'FR-15': {
        'id': 'FR-15',
        'title': 'Card-Not-Present Anomaly',
        'category': 'Card E-Commerce Fraud',
        'weight': 12,
        'severity': 'HIGH',
        'description': 'High-value e-commerce purchase combined with foreign IP, VPN, or off-hours execution.',
        'sop': 'Review 3D-Secure authentication result and merchant risk profile; initiate card dispute if unauthorized.',
    },
    'FR-16': {
        'id': 'FR-16',
        'title': 'Unusual Transaction Time',
        'category': 'Behavioral Timing',
        'weight': 4,
        'severity': 'LOW',
        'description': 'Transaction executed during deep night hours (00:00 - 05:00) outside normal customer profile.',
        'sop': 'Analyze concurrent session telemetry and behavioral biometrics.',
    },
    'FR-17': {
        'id': 'FR-17',
        'title': 'New Device + New Beneficiary',
        'category': 'Compound ATO Risk',
        'weight': 12,
        'severity': 'HIGH',
        'description': 'Dangerous combination: unverified device sending funds to newly registered beneficiary.',
        'sop': 'Step-up challenge mandatory. Confirm payee details with customer through secondary trusted channel.',
    },
    'FR-18': {
        'id': 'FR-18',
        'title': 'Credential Reset + New Device',
        'category': 'ATO Hard Trigger',
        'weight': 18,
        'severity': 'CRITICAL',
        'is_hard_trigger': True,
        'description': 'Recent password reset followed immediately by outbound transfer from an unfamiliar device.',
        'sop': 'Critical account takeover alert. Immediate session termination and outbound hold.',
    },
    'FR-19': {
        'id': 'FR-19',
        'title': 'New Cross-Border Beneficiary + High Value',
        'category': 'Capital Flight / Cross-Border',
        'weight': 14,
        'severity': 'HIGH',
        'description': 'Cross-border SWIFT or interbank transfer to a foreign counterparty never previously transacted with.',
        'sop': 'Cross-border compliance check. Verify commercial invoices and regulatory declaration.',
    },
    'FR-20': {
        'id': 'FR-20',
        'title': 'Incomplete Corporate Approval',
        'category': 'Corporate Governance',
        'weight': 25,
        'severity': 'CRITICAL',
        'is_hard_trigger': True,
        'description': 'Corporate payment (SIOP/SWIFT Light) submitted without completing mandatory maker-checker multi-level approvals.',
        'sop': 'Governance breach. Block release and escalate to Corporate Banking Relationship Manager.',
    },
}

COUNTER_EVIDENCE_CATALOG = [
    {
        'id': 'CE-01',
        'title': 'Trusted Device + Established Beneficiary',
        'deduction': 12,
        'description': 'Transaction executed from customer verified primary device to an established beneficiary with 3+ prior successful transactions.',
    },
    {
        'id': 'CE-02',
        'title': 'Recurring / Scheduled Payment',
        'deduction': 10,
        'description': 'Standing order, payroll, or scheduled recurring payment matching expected rhythm.',
    },
    {
        'id': 'CE-03',
        'title': 'Diaspora Consistent Pattern',
        'deduction': 10,
        'description': 'Legitimate cross-border remittance by a verified Diaspora customer to family in DRC.',
    },
    {
        'id': 'CE-04',
        'title': 'Corporate Supplier + Approvals Complete',
        'deduction': 15,
        'description': 'Corporate mining/logistics supplier payment with dual maker-checker approvals fully completed.',
    },
    {
        'id': 'CE-05',
        'title': 'High-Net-Worth Baseline Alignment',
        'deduction': 8,
        'description': 'High nominal amount is within normal historical baseline for Premium, Prestige, Infinite, or Corporate account.',
    },
]
